### ISSUE TITLE
cmake fails if DRI package not installed (mesa-common-dev)

### ISSUE THREAD

**Issue by edgecase14** [caramelli/yagears#1]
building on Ubuntu 20.10, CMakeLists.txt should handle this case
cmake output:
....
-- Checking for modules 'gbm;libdrm;libevdev'
--   Found gbm, version 20.2.6
--   Found libdrm, version 2.4.102
--   Found libevdev, version 1.9.1
Package dri was not found in the pkg-config search path.
Perhaps you should add the directory containing `dri.pc'
to the PKG_CONFIG_PATH environment variable
No package 'dri' found
CMake Error at CMakeLists.txt:218 (string):
  string sub-command STRIP requires two arguments.

Package dri was not found in the pkg-config search path.
Perhaps you should add the directory containing `dri.pc'
to the PKG_CONFIG_PATH environment variable
No package 'dri' found
CMake Error at CMakeLists.txt:220 (string):
  string sub-command STRIP requires two arguments.

CMake Error at CMakeLists.txt:221 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.

CMake Error at CMakeLists.txt:222 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.

-- Checking for module 'bcm_host'
--   No package 'bcm_host' found
....

**Comment by caramelli** [comment]
Yes, it will be better to avoid these error messages. In the CMakeLists.txt file, replace:

	pkg_check_modules(DRM gbm libdrm libevdev)

with:

	pkg_check_modules(DRM dri gbm libdrm libevdev)

I will fix it in the next version. Thanks.
